name = "TypeUtils"
uuid = "c3b1956e-8857-4d84-9b79-890df85b1e67"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.3.5"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Requires = "1.3"
TwoDimensional = "0.3"
julia = "0.7, 1"

[extensions]
TypeUtilsTwoDimensionalExt = "TwoDimensional"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TwoDimensional = "1907e7ba-7586-4310-a2ba-dd01462aeb50"

[targets]
test = ["Test", "TwoDimensional"]

[weakdeps]
TwoDimensional = "1907e7ba-7586-4310-a2ba-dd01462aeb50"
